version: '3.8'
services:
  unifi-mongo:
    image: mongo:3.6
    container_name: unifi-mongo
    networks:
      - unifi-internal
    restart: always
    volumes:
      - unifi-db:/data/db
      - unifi-dbcfg:/data/configdb

  unifi-controller:
    build: .
    image: unifi-controller-local:10.4.57
    container_name: unifi-controller
    depends_on:
      - unifi-mongo
    init: true
    networks:
      - unifi-internal
      - dokploy-network
    restart: always
    labels:
      - "traefik.enable=true"
      # Ganti unifi.domainanda.com dengan domain asli Anda
      - "traefik.http.routers.unifi-gui.rule=Host(`unifi.sknddev.com`)"
      - "traefik.http.routers.unifi-gui.entrypoints=websecure"
      # Wajib beritahu Traefik network mana yang dipakai (karena ada 2 network)
      - "traefik.docker.network=dokploy-network"
      # Konfigurasi vital untuk Backend UniFi (HTTPS)
      - "traefik.http.services.unifi-gui.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi-gui.loadbalancer.server.scheme=https"
      # Bypass verifikasi SSL internal jika sertifikat bawaan UniFi self-signed
      - "traefik.http.services.unifi-gui.loadbalancer.server.serversTransport=insecureTransport"
    volumes:
      - unifi-dir:/unifi
      - unifi-data:/unifi/data
      - unifi-log:/unifi/log
      - unifi-cert:/unifi/cert
      - unifi-init:/unifi/init.d
      - unifi-run:/var/run/unifi
      - unifi-backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://unifi-mongo/unifi
      STATDB_URI: mongodb://unifi-mongo/unifi_stat
      DB_NAME: unifi
      TZ: ${TZ}
      JVM_MAX_HEAP_SIZE: ${JVM_MAX_HEAP_SIZE}
      JVM_INIT_HEAP_SIZE: ${JVM_INIT_HEAP_SIZE}
      UNIFI_STDOUT: ${UNIFI_STDOUT}
      SYSTEM_IP: ${SYSTEM_IP}

  unifi-logs:
    image: bash
    container_name: unifi-logs
    depends_on:
      - unifi-controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - unifi-log:/unifi/log

volumes:
  unifi-db:
  unifi-dbcfg:
  unifi-data:
  unifi-log:
  unifi-cert:
  unifi-init:
  unifi-dir:
  unifi-run:
  unifi-backup:

networks:
  unifi-internal:
  dokploy-network:
    external: true
